### PR TITLE
backend CI issue soln

### PR DESCRIPTION
**Pull request by Sahil1479**
@Tanuj22 
As you know our backend CI was failing continuously. So I made few changes in student model ( added @deconstructible decorator above ProgramAndBranch class ) 
It worked for me. Please verify it once.

### CODE REVIEW

**Comment by Tanuj22** [comment]
Nice! Just curious, why did this fix the issue?

**Comment by Tanuj22** [comment]
Nice! Just curious, why did this fix the issue?

**Comment by Sahil1479** [comment]
It is class decorator that allow the decorated class to be serialized by the migrations subsystem.
You can refer [https://docs.djangoproject.com/en/3.2/topics/migrations/#adding-a-deconstruct-method](url)

**Comment by Sahil1479** [comment]
One more thing I forgot to add conditional render statement, i.e. render component iff data is present. I will fix it by tomorrow itself.

**Pull request merged**
